### ISSUE TITLE
Problems running gosu $APP_USER:$APP_USER npm install after PRs #12, #13 and #14

### ISSUE THREAD

**Issue by willowmagrini** [InfoAmazonia/visaguas#15]
@studiocuboweb I've tested locally and wasn't able to get the docker running after merging the PRs 12, 13 and 14:
```> contextify@0.1.15 install /home/node/app/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/home/node/app/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function 'static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)':
../src/contextify.cc:131:68: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/node/.cache/node-gyp/8.17.0/include/node/v8.h:26:0,
                 from /home/node/.cache/node-gyp/8.17.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/node/.cache/node-gyp/8.17.0/include/node/v8.h:3901:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/node/.cache/node-gyp/8.17.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:150:16: error: 'class v8::ObjectTemplate' has no member named 'SetAccessCheckCallbacks'; did you mean 'SetAccessCheckCallback'?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^~~~~~~~~~~~~~~~~~~~~~~
../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)':
../src/contextify.cc:182:80: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/node/.cache/node-gyp/8.17.0/include/node/v8.h:26:0,
                 from /home/node/.cache/node-gyp/8.17.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/node/.cache/node-gyp/8.17.0/include/node/v8.h:3454:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/node/.cache/node-gyp/8.17.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)':
../src/contextify.cc:209:67: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/node/.cache/node-gyp/8.17.0/include/node/v8.h:26:0,
                 from /home/node/.cache/node-gyp/8.17.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/node/.cache/node-gyp/8.17.0/include/node/v8.h:3454:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/node/.cache/node-gyp/8.17.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:210:71: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/node/.cache/node-gyp/8.17.0/include/node/v8.h:26:0,
                 from /home/node/.cache/node-gyp/8.17.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/node/.cache/node-gyp/8.17.0/include/node/v8.h:3454:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/node/.cache/node-gyp/8.17.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
contextify.target.mk:101: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: Leaving directory '/home/node/app/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.10.41-1-MANJARO
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/app/node_modules/contextify
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-06-08T22_27_57_155Z-debug.log
The command '/bin/sh -c chown -R $APP_USER:$APP_USER $HOME/app &&   gosu $APP_USER:$APP_USER npm install' returned a non-zero code: 1
```

**Comment by willowmagrini** [comment]
We've made a copy of the repository on gitlab (in order to use CI/CD to deploy) and had to make some modifications to get it running before those PRs. here is a copy of our Dockerfile (Working before the PRs) 
https://gist.github.com/willowmagrini/f1ce44af18316b97347df86949d0c2d6
We've also tried with node:8 without success

**Comment by studiocuboweb** [comment]
Por que você está usando o node-gyp para fazer o build? Eu não conhecia essa ferramenta e até onde eu li, serve para compilar add-ons em C++ para node 

_Addons are dynamically-linked shared objects written in C++. The require() function can load addons as ordinary Node. js modules. Addons provide an interface between JavaScript and C/C++ libraries. ... V8 provides the mechanisms for creating objects, calling functions, etc._

Me corrija se eu estiver errado.

De qualquer forma rodei esse procedimento: 

1. Copiei [esse Dockerfile que vc me passou ](https://gist.github.com/willowmagrini/f1ce44af18316b97347df86949d0c2d6)

2. Buildando novamente a imagem do docker:
docker-compose build --no-cache
2.1 PROBLEMA: Precisei mudar o keyserver conforme esse commit: https://github.com/InfoAmazonia/visaguas/commit/222d8f39e7520ffe9c01f73a5a30c70b739c761e

3. Ligando o container
docker-compose up -d

4. Entrei no bash do container
docker-compose exec app bash

5. instalei o node-gyd dentro do bash do docker
````
npm install -g node-gyp
````

6. Rodei o comando 

````
node-gyp rebuild
````
6.1 PROBLEMA: versão do node desatualizada. Atualizei para 10 conforme commit https://github.com/InfoAmazonia/visaguas/commit/222d8f39e7520ffe9c01f73a5a30c70b739c761e

6.2 PROBLEMA: Python desatualizado. Atualizei [conforme esse procedimento](https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/) e na sequencia 

````
mv /usr/local/bin/python3.7 /usr/bin/python3
````

6.3 PROBLEMA: precisei criar um arquivo binding.gyp na raiz da aplicação com o seguinte código

````
{
"targets": [
{
"target_name": "binding",
"sources": [ "build/Release/binding.node" ]
}
]
}
````

7. Rodei o comando novamente

````
node-gyp rebuild
````

Resultado:
Não apareceu nenhuma mensagem de erro e foi criada uma pasta build conforme essa imagem:
![Screen Shot 2021-06-23 at 22 53 42](https://user-images.githubusercontent.com/32527574/123190445-ec8f2b80-d475-11eb-9eb7-c6f8ecb186c3.png)

Eu não fui mais adiante para entender oq fazer com esses arquivos buildados, mas creio que esse passo a passo deu certo, pois não gerou nenhum erro

Observações:

O projeto / Docker foi montado para utilizar o grunt como builder para as views :

````
mkdir -p dist && ./node_modules/grunt-cli/bin/grunt build
````

O package.json desse projeto original e o próprio docker não possuem nenhuma instalação node-gyp então eu creio que ele foi concebido sem essa ferramenta.

Já para a aplicação em node, o tradicional node  index.js já resolve a questão.

Com o procedimento no readme.md já é possível subir a aplicação com o docker e acessá-la.
Tb é possível compilar os assets utilizando o grunt. Se você estiver fora do docker e utilizar o node 10 do servidor e rodar um node index.js já nao da para subir a aplicação?

No meu localhost com o Docker consigo acessar o site conforme print e todos os procedimentos funcionam mesmo com o node 10.
![Screen Shot 2021-06-23 at 23 11 15](https://user-images.githubusercontent.com/32527574/123191947-61fbfb80-d478-11eb-92df-bd635991b98c.png)

Para organizar as coisas eu fechei os 3 pull requests  e deletei seus respectivos branchs:

Fix angular upgrade (pull request)
fix-angular-upgrade (branch)

Underscore update (pull request) 
underscore-update (branch)

Upgrade grunt and dependencies (pull request)
grunt-update (branch)

Criei esse novo que contém os 3 ajustes em um só lugar:
https://github.com/InfoAmazonia/visaguas/pull/16

Me avisa se deu certo? Qualquer dúvida so chamar.

**Comment by willowmagrini** [comment]
@studiocuboweb não fomos nós que criamos esse dockerfile, não consigo te responder o porque da utilização do node-gyp.
Dei um checkout para o seu branch aqui e um docker build mas seguimos com o mesmo erro aqui. Você conseguiu buildar a imagem normalmente a partir do branch merge-upgrades?

**Comment by studiocuboweb** [comment]
Oi @willowmagrini Sim, eu consigo buildar a imagem normalmente a partir do branch merge-upgrades. Eu deletei a imagem e o container diversas vezes e rodei docker-compose build --no-cache e docker-compose build.

Após buildar eu rodo o docker-compose up e acesso a aplicação normalmente via localhost:3000

Investiguei aqui e o comando node-gyp rebuild está sendo executado após o npm install no Dockerfile na linha 26:

`````
RUN chown -R $APP_USER:$APP_USER $HOME/app && \
  gosu $APP_USER:$APP_USER npm install
`````

Esse comando mostra esse log na execução do docker-compose build (--no-cache)
`````

Step 17/21 : RUN chown -R $APP_USER:$APP_USER $HOME/app &&   gosu $APP_USER:$APP_USER npm install
 ---> Running in a66157bc6450

> visaguas@0.1.0 install /home/node/app
> node-gyp rebuild

make: Entering directory '/home/node/app/build'
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/node/app/build'

`````

Olhei o package.json e não consegui descobrir onde está o gatilho para a execução do node-gyp rebuild com o npm install e também não ficou claro para mim a sua função. De qualquer forma, [achei esse post aqui](https://stackoverflow.com/questions/39709084/run-npm-install-without-node-gyp-rebuild?rq=1) orientando como desativar esse comando.  No package.json acrescentei essa linha:

`````
 "install" : "echo"
`````

[nesse commit](https://github.com/InfoAmazonia/visaguas/commit/4e8f3df9de29aede715c89f6505fe11a70013ab3)

E ao rodar o docker-compose build novamente o log aparece dessa forma:

`````
Step 17/21 : RUN chown -R $APP_USER:$APP_USER $HOME/app &&   gosu $APP_USER:$APP_USER npm install
 ---> Running in 5c3bd380a9ec

> visaguas@0.1.0 install /home/node/app
> echo


> visaguas@0.1.0 postinstall /home/node/app
> mkdir -p dist && ./node_modules/grunt-cli/bin/grunt build
`````

e o build também é concluído com sucesso.

Após rodar o docker-compose up novamente, consigo abrir a aplicação em localhost:3000

Ou seja... por aqui a aplicação está abrindo normalmente e o build concluído com sucesso (eu uso Mac, não sei se pode ser algo do sistema operacional).

Tenta ver se esse fix do install: echo funciona?

Se não, já tentou apagar a imagem e o container e rodar um docker-compose build --no-cache?

**Comment by willowmagrini** [comment]
Continuasmos travados no build aqui. Pedi para outra pessoa clonar o repo, dar checkout para o branch merge-upgrades e executar o docker-compos up, essa pessoa nunca havia clonado o repo ou construido essa imagem. o erro foi o mesmo do meu computador:
![image](https://user-images.githubusercontent.com/8497431/128016817-772ed3d0-a03e-4c68-8ace-8a57c98dd26a.png)

**Comment by studiocuboweb** [comment]
@willowmagrini vc fez o pull e pegou a ultima versão do package.json com aquele esquema do install:echo?

Tá complicado... vou tentar rodar isso em uma máquina com ubuntu tb para ver se eu consigo reproduzir esse erro.

**Comment by willowmagrini** [comment]
O usuário de teste fez o pull ontem, utilizando o branch  merge-upgrades. Pelo que observei esse branch ja esta com essa alteração commitada.

**Comment by vgeorge** [comment]
Pessoal, os módulos que estão causando o problema são o `d3` e `grunt-browserify`, é preciso fazer minor upgrades deles. Também recomendaria usar a versão LTS do node.  Eu consegui fazer um build com os seguintes passos:

1. Instalar o nvm https://github.com/nvm-sh/nvm
2. `nvm install 14`
3.  `nvm use 14`
4.  Substituir o package.json por este:

```
{
  "homepage": "https://1visag.infoamazonia.org/",
  "name": "visaguas",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "postinstall": "mkdir -p dist && ./node_modules/grunt-cli/bin/grunt build",
    "start": "node index.js",
    "clean": "gh-pages-clean",
    "predeploy": "NODE_ENV=production npm run build",
    "deploy": "gh-pages -d dist"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/InfoAmazonia/visaguas.git"
  },
  "bugs": {
    "url": "https://github.com/InfoAmazonia/visaguas/issues"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular": "1.8.0",
    "angular-ui-router": "0.2.10",
    "ng-dialog": "0.3.10",
    "async": "0.9.0",
    "body-parser": "1.6.7",
    "compression": "1.0.11",
    "csv": "3",
    "d3": "3.5.17",
    "csv-parse": "4.12.0",
    "csv-stringify": "2.0.0",
    "dotenv": "1.0.0",
    "express": "4.8.7",
    "grunt": "0.4.5",
    "browserify": "9.0.3",
    "browserify-shim": "3.8.3",
    "grunt-browserify": "3.8.0",
    "grunt-cli": "0.1.13",
    "grunt-contrib-copy": "0.5.0",
    "grunt-contrib-jade": "0.12.0",
    "grunt-contrib-less": "0.11.4",
    "grunt-contrib-uglify": "0.5.1",
    "grunt-contrib-watch": "0.6.1",
    "napa": "0.4.1",
    "underscore": "1.7.0"
  },
  "browser": {
    "angular": "./node_modules/angular/angular.js"
  },
  "browserify-shim": {
    "angular": "angular"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "devDependencies": {
    "gh-pages": "^2.2.0"
  }
}
```

5. `npm i`

O dockerfile foi criado para facilitar o deploy em uma infrastrutura que tínhamos, parece-me que ele não é necessário para um ambiente de desenvolvimento.

**Comment by studiocuboweb** [comment]
Depois gostaria de saber como você chegou nessas duas bibliotecas. 

Aqui eu consegui reproduzir o erro em uma máquina Ubuntu 18.04 (sempre tentando pelo docker)

cheguei a essa questão aqui:
https://www.npmjs.com/package/contextify

No ubuntu ele fazia isso:
````
> contextify@0.1.15 install /home/node/app/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild
> make: Entering directory '/home/node/app/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
`````

No Mac:
`````
> visaguas@0.1.0 install /home/node/app
> node-gyp rebuild
> mkdir -p dist && ./node_modules/grunt-cli/bin/grunt build
`````

Não entendo porque esse comportamento diferente entre ubuntu e mac... de qq forma pelo oq eu li no link do pacote o contextify está mergeado dentro do Node e não é mais utilizado (inclusive está com status UNMAINTAINED).

Também li recomendações para instalar e usar o nvm / versão node LTS.

https://blog.m157q.tw/posts/2017/09/01/error-contextify-0-1-15-install-node-gyp-rebuild/

Posso mudar o Dockerfile para contemplar esses ajustes?

**Comment by willowmagrini** [comment]
@studiocuboweb como utilizamos o Docker no ambiente de produção também acho que é necessária essa mudança através do Dockerfile

**Comment by bwstefano** [comment]
@studiocuboweb, @willowmagrini: importante notar a [URL declarada no package.json](https://github.com/InfoAmazonia/visaguas/blob/0cccc97f1b38f73052973e15743c2af40e0d399c/package.json#L2). Ela está num endereço de testes antigo nosso (`https://1visag.infoamazonia.org/`) e deveria ser `https://visaguas.infoamazonia.org/`

**Comment by vgeorge** [comment]
@studiocuboweb eu fui removendo cada um dos módulos e depois executei npm install para ver se dava problema. Estão acontecendo estes erros estranhos porque na época não foi gerado um `package-lock.json` (talvez porque não houvesse suporte do npm) e a árvore de dependências não é a mesma. Vai ser bem difícil restaurar exatamente a mesma árvore, por isso recomendei fazer os minors upgrades. Assim a API do módulos alterados não muda (ou não deveriam) e fica mais fácil fazer com que o app funcione com as versões atualizadas. Depois que houver o upgrade é altamente recomendável fazer o commit do package-lock.json (ou yarn.lock se vcs preferirem o yarn).

**Comment by bwstefano** [comment]
@vgeorge, no package.json que você [mencionou acima](#issuecomment-891957625), as versões de algumas bibliotecas que o @studiocuboweb atualizou (underscore, grunt, angular e node no dockerfile) e cujas mudanças foram reunidas no PR #16, acabaram voltando para suas versões iniciais.

A gente pediu pra ele fazer essas atualizações por questões de segurança apontadas pelo Dependabot. Ele basicamente só atualizou as versões no package.json, mas ainda teve que fazer [este ajuste num arquivo](https://github.com/InfoAmazonia/visaguas/pull/16/commits/8557affb906304574f3218947791f14ec4bc6150), que foi necessário para atualizar o angular.

Você acha que seria possível, então, deixar o package.json como está e só voltar as versões do `d3 `e `grunt-browserify` para as que você conseguiu fazer rodar? Ou talvez estes dois e todos os demais módulos `grunt`, mas manter o `underscore` e `angular`, pelo menos, junto com o `node` que está declarado no dockerfile.

**Comment by bwstefano** [comment]
@vgeorge, o @studiocuboweb fez uns testes por aqui. Ele montou uma página com o Ubuntu 18 e subiu o site [aqui](http://18.230.118.229:3000/dados/abastecimento/agua_rede_geral/). Este site tem todos os ajustes do PR #16, Inclusive as versões do `grunt` e do `underscore` atualizadas. O `underscore` aqui é o 1.13.0.

Aí ele atualizou o Dockerfile para pegar a versão node:lts e o `grunt-browserify` + `d3` conforme sua orientação. Então o `build` e o `docker-compose up` rolaram no Ubuntu 18.

A única coisa que ficou errado é que os gráficos do mapa não rolaram legal, algo que parece ser a ver com o arquivo `vendor.js`. Veja:

![image](https://user-images.githubusercontent.com/11841075/128101199-5ca8612a-6878-441b-b7c0-0247ed9bad55.png)

Numa olhada rápida, você consegue imaginar se isso é algum módulo que não poderia ter sido atualizado? Daí poderíamos deixá-lo pra trás. Só tentando aqui não perder o trabalho do Paulo de atualizar todos esse módulos.

O Paulo fez dois novos commits no PR #16: um com o upgrade de versão no Dockerfile e outro com as atualizações do package.json para ficar mais fácil ver o que foi feito.
